mm-madvise-introduce-process_madvise-syscall-an-external-memory-hinting-api-fix-fix
fix i386 build

mm/madvise.c: In function process_madvise_vec:
mm/madvise.c:1168:15: error: storage size of iovec isnt known
  struct iovec iovec;

Cc: Florian Weimer <fw@deneb.enyo.de>
Cc: Minchan Kim <minchan@kernel.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>