lib-test_bitmapc-add-for_each_set_clump-test-cases-checkpatch-fixes
ERROR: that open brace { should be on the previous line
#151: FILE: lib/test_bitmap.c:648:
+static struct clump_test_data_params clump_test_data[] __initdata =
+				      { {{0}, 2, 0, 64, 8, clump_exp1},

ERROR: that open brace { should be on the previous line
#161: FILE: lib/test_bitmap.c:658:
+	for(i = 0; i < clump_test_data[index].count; i++)
+	{

ERROR: space required before the open parenthesis '('
#161: FILE: lib/test_bitmap.c:658:
+	for(i = 0; i < clump_test_data[index].count; i++)

ERROR: that open brace { should be on the previous line
#169: FILE: lib/test_bitmap.c:666:
+static void __init execute_for_each_set_clump_test(unsigned int index)
+{

WARNING: suspect code indent for conditional statements (8, 8)
#173: FILE: lib/test_bitmap.c:670:
+	for_each_set_clump(start, clump, clump_test_data[index].data,
[...]
+	expect_eq_clump(start, clump_test_data[index].limit, clump_test_data[index].exp,

ERROR: that open brace { should be on the previous line
#180: FILE: lib/test_bitmap.c:677:
+static void __init test_for_each_set_clump(void)
+{

total: 5 errors, 1 warnings, 174 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/lib-test_bitmapc-add-for_each_set_clump-test-cases.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Syed Nayyar Waris <syednwaris@gmail.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>